/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as EconomyImport } from './routes/economy'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as VesselsIndexImport } from './routes/vessels/index'
import { Route as LocationsIndexImport } from './routes/locations/index'
import { Route as VesselsIdImport } from './routes/vessels/$id'
import { Route as ProductsIdImport } from './routes/products/$id'
import { Route as LocationsIdImport } from './routes/locations/$id'

// Create/Update Routes

const EconomyRoute = EconomyImport.update({
  id: '/economy',
  path: '/economy',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const VesselsIndexRoute = VesselsIndexImport.update({
  id: '/vessels/',
  path: '/vessels/',
  getParentRoute: () => rootRoute,
} as any)

const LocationsIndexRoute = LocationsIndexImport.update({
  id: '/locations/',
  path: '/locations/',
  getParentRoute: () => rootRoute,
} as any)

const VesselsIdRoute = VesselsIdImport.update({
  id: '/vessels/$id',
  path: '/vessels/$id',
  getParentRoute: () => rootRoute,
} as any)

const ProductsIdRoute = ProductsIdImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => rootRoute,
} as any)

const LocationsIdRoute = LocationsIdImport.update({
  id: '/locations/$id',
  path: '/locations/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/economy': {
      id: '/economy'
      path: '/economy'
      fullPath: '/economy'
      preLoaderRoute: typeof EconomyImport
      parentRoute: typeof rootRoute
    }
    '/locations/$id': {
      id: '/locations/$id'
      path: '/locations/$id'
      fullPath: '/locations/$id'
      preLoaderRoute: typeof LocationsIdImport
      parentRoute: typeof rootRoute
    }
    '/products/$id': {
      id: '/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ProductsIdImport
      parentRoute: typeof rootRoute
    }
    '/vessels/$id': {
      id: '/vessels/$id'
      path: '/vessels/$id'
      fullPath: '/vessels/$id'
      preLoaderRoute: typeof VesselsIdImport
      parentRoute: typeof rootRoute
    }
    '/locations/': {
      id: '/locations/'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsIndexImport
      parentRoute: typeof rootRoute
    }
    '/vessels/': {
      id: '/vessels/'
      path: '/vessels'
      fullPath: '/vessels'
      preLoaderRoute: typeof VesselsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/economy': typeof EconomyRoute
  '/locations/$id': typeof LocationsIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/vessels/$id': typeof VesselsIdRoute
  '/locations': typeof LocationsIndexRoute
  '/vessels': typeof VesselsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/economy': typeof EconomyRoute
  '/locations/$id': typeof LocationsIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/vessels/$id': typeof VesselsIdRoute
  '/locations': typeof LocationsIndexRoute
  '/vessels': typeof VesselsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/economy': typeof EconomyRoute
  '/locations/$id': typeof LocationsIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/vessels/$id': typeof VesselsIdRoute
  '/locations/': typeof LocationsIndexRoute
  '/vessels/': typeof VesselsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/economy'
    | '/locations/$id'
    | '/products/$id'
    | '/vessels/$id'
    | '/locations'
    | '/vessels'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/economy'
    | '/locations/$id'
    | '/products/$id'
    | '/vessels/$id'
    | '/locations'
    | '/vessels'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/economy'
    | '/locations/$id'
    | '/products/$id'
    | '/vessels/$id'
    | '/locations/'
    | '/vessels/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  EconomyRoute: typeof EconomyRoute
  LocationsIdRoute: typeof LocationsIdRoute
  ProductsIdRoute: typeof ProductsIdRoute
  VesselsIdRoute: typeof VesselsIdRoute
  LocationsIndexRoute: typeof LocationsIndexRoute
  VesselsIndexRoute: typeof VesselsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  EconomyRoute: EconomyRoute,
  LocationsIdRoute: LocationsIdRoute,
  ProductsIdRoute: ProductsIdRoute,
  VesselsIdRoute: VesselsIdRoute,
  LocationsIndexRoute: LocationsIndexRoute,
  VesselsIndexRoute: VesselsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/economy",
        "/locations/$id",
        "/products/$id",
        "/vessels/$id",
        "/locations/",
        "/vessels/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/economy": {
      "filePath": "economy.tsx"
    },
    "/locations/$id": {
      "filePath": "locations/$id.tsx"
    },
    "/products/$id": {
      "filePath": "products/$id.tsx"
    },
    "/vessels/$id": {
      "filePath": "vessels/$id.tsx"
    },
    "/locations/": {
      "filePath": "locations/index.tsx"
    },
    "/vessels/": {
      "filePath": "vessels/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
